config/routes.rb
Rails.application.routes.draw do

  # ログインしている場合は投稿一覧がroot
  authenticated :user do
    root to: 'places#index', as: :user_root
  end

  root to: 'pages#index'

  get 'choices/new'
  get 'spots/new'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get 'pages/index'
  get 'pages/about'
  get 'places/myplace'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :comments
  resources :places

end

app/models/place.rb
class Place < ApplicationRecord
  validate :add_error_sample

  validates :name, presence: true
  validates :description, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :images, presence: { message: "をアップロードしてください" }

  after_validation :remove_unnecessary_error_messages

  # 緯度、経度から住所を取得
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  has_many_attached :images
  belongs_to :area
  belongs_to :user

  def add_error_sample
    # 地図上の選択が空のときにエラーメッセージを追加する
    if latitude.nil?
      errors.add(:base, "地図上に場所を設定してください")
    end
  end

  def remove_unnecessary_error_messages
    # 緯度、経度のエラーメッセージを削除
    if latitude.nil?
      errors.messages.delete(:latitude)
      errors.messages.delete(:longitude)
    end
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  # 投稿一覧画面を表示
  def index
    @places = Place.all
    gon.places = @places
    gon.url = []

    # 各placeのimageの1枚目のURLのみを取得
    @places.each_with_index do |place, i|
      gon.url[i] = url_for(place.images.first) if place.images.count != 0
    end

  end

  # GET /places/1
  # GET /places/1.json
  # 投稿詳細画面を表示
  def show
    gon.lat = @place.latitude
    gon.lng = @place.longitude
  end

  # 自分の投稿の一覧を表示
  def myplace
    @places = Place.where(user_id: current_user.id)
    gon.places = @places
    gon.url = []
    @places.each_with_index do |place, i|
      gon.url[i] = url_for(place.images.first) if place.images.count != 0
    end
  end

  # GET /places/new
  # 新しいインスタンスの生成
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  # 投稿編集画面を表示
  def edit
    gon.lat = @place.latitude
    gon.lng = @place.longitude
  end

  # POST /places
  # POST /places.json
  # 新規投稿を作成
  def create
    @place = current_user.places.new(place_params)
    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'スポットが投稿されました' }
        format.json { render :show, status: :created, location: @place }
      else
        # binding.pry
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  # 投稿内容を更新
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'スポットの詳細が変更されました' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  # 投稿を削除
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_myplace_path, notice: 'スポットが削除されました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:user_id, :name, :description, :area_id, :address, :latitude, :longitude, images:[])
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |f| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label :name, class: "col-3 col-md-2 col-form-label" %>
    <%= f.text_field :name, class: "col-8 col-md-9" %>
  </div>

  <div class="form-group row">
    <%= f.label :description, class: "col-3 col-md-2 col-form-label" %>
    <%= f.text_area :description, class: "col-8 col-md-9" %>
  </div>

  <% if controller.action_name == 'edit' %>
    <div class="form-group row">
      <%= f.label :park, class: "col-3 col-md-2 col-form-label" %>
      <%= f.collection_select :park_id, Park.all, :id, :name, {selected: place.area.park.id}, {class: 'edit-park col-8 col-md-9'} %>
    </div>
    <div class="form-group row">
      <%= f.label :area, class: "col-3 col-md-2 col-form-label" %>
      <%= f.select :area_id, options_for_select(Area.all.map{|area|[area[:name], area[:id], {'data-val'=>area[:park_id]}]}, {selected: place.area_id}), {}, {class: 'edit-area col-8 col-md-9'} %>
    </div>

  <% else %>
    <div class="form-group row">
      <%= f.label :park, class: "col-3 col-md-2 col-form-label" %>
      <%= f.collection_select :park_id, Park.all, :id, :name, {prompt: "パークを選択してください"}, {class: 'new-park col-8 col-md-9'} %>
    </div>
    <div class="form-group row">
      <%= f.label :area, class: "col-3 col-md-2 col-form-label" %>
      <%= f.select :area_id, options_for_select(Area.all.map{|area|[area[:name], area[:id], {'data-val'=>area[:park_id]}]}), {prompt: "エリアを選択してください"}, {class: 'new-area col-8 col-md-9'} %>
    </div>

  <% end %>

  <div class="form-group">
    <%= f.hidden_field :address %>
  </div>

  <div class="form-group">
    <%= f.hidden_field :latitude, id: "lat" %>
  </div>

  <div class="form-group">
    <%= f.hidden_field :longitude, id: "lng" %>
  </div>

  <div class="form-group row input-photo mb-2">
    <div class="input-group">
      <div class="custom-file col-md-9 col-8 offset-1">
        <%= f.file_field :images, multiple: true ,class: "custom-file-input", id: "button-addon", aria: {describedby: "button-addon"} %>
        <%= f.label "ファイルを選択...", class: "custom-file-label", for: "button-addon", data: {browse: "参照"} %>
      </div>
      <div class="input-group-append">
        <button type="button" class="btn btn-outline-secondary reset" id="button-addon2">取消</button>
      </div>
    </div>
  </div>

  <div class="row">
    <div id="map" class="col-10 offset-1 my-4"></div>
  </div>

<div class="actions form-group mt-3">
  <% if request.referer&.include?("/places/myplace") %>
    <%= f.submit '更新する', class: "btn btn-orange" %>
  <% else %>
    <%= f.submit '投稿する', class: "btn btn-orange" %>
  <% end %>
</div>

<% end %>

<% if controller.action_name == 'edit' %>
  <%= javascript_include_tag 'edit-place.js' %>
<% else %>
  <%= javascript_include_tag 'new-place.js' %>
<% end %>

app/views/places/edit.html.erb
<div class="container my-4">
  <h1>スポットを編集する</h1>

  <%= render 'form', place: @place %>

  <%= link_to '詳細を見る', @place %> |
  <%= link_to '一覧に戻る', :back %>
</div>

<script src="//maps.google.com/maps/api/js?key=<%= Rails.application.credentials.dig(:google, :api_key) %>&callback=initEditMap" async defer></script>

app/views/places/index.html.erb
<div class="all-spots-containter">
  <div class="container my-4">
    <h1>投稿一覧</h1>

    <div id="map" class="w-auto m-3"></div>

    <div class="table-responsive">
      <table class="table">

        <tbody>
          <% @places.each do |place| %>
            <tr>
              <td><strong>ひとこと</strong><br/>
                <%= place.name %></td>
              <td class="area-name"><p class="text-primary bg-blue"><%= place.area.name %></p></td>
              <td><%= link_to '詳細', place, class: "btn btn-orange my-auto" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script src="//maps.google.com/maps/api/js?key=<%= Rails.application.credentials.dig(:google, :api_key) %>&callback=initViewMap" async defer></script>

app/views/places/myplace.html.erb
<div class="myplace">
  <div class="container my-4">
    <h1>My投稿</h1>

    <div id="map" class="w-auto m-3"></div>

    <div class="table-responsive">
      <table class="table">
        <tbody>
          <% @places.each do |place| %>
            <tr>
              <td><strong>ひとこと</strong><br/>
                <%= place.name %></td>
              <td>
                <div class="btns">
                  <%= link_to '詳細', place, class: "btn btn-orange mx-md-4" %>
                  <%= link_to '編集', edit_place_path(place), class: "btn btn-orange mx-md-4" %>
                  <%= link_to '削除', place, method: :delete, data: { confirm: '本当にこのスポットを削除してもよろしいですか？' }, class: "btn btn-danger mx-md-4" %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script src="//maps.google.com/maps/api/js?key=<%= Rails.application.credentials.dig(:google, :api_key) %>&callback=initViewMap" async defer></script>

app/views/places/new.html.erb
<div class="container my-4">
  <h1>新規スポットを投稿する</h1>
  
  <%= render 'form', place: @place %>
</div>

<script src="//maps.google.com/maps/api/js?key=<%= Rails.application.credentials.dig(:google, :api_key) %>&callback=initNewMap" async defer></script>

app/views/places/show.html.erb
<div class="show-container">
  <div class="container my-4">
    <div class="under-blue">
      <h2 class="place-head text-dark"><strong><%= @place.name %></strong></h2>
      <p class="text-primary bg-blue place-head ml-4">
        <%= @place.area.park.name %>/<%= @place.area.name %>
      </p>
    </div>

    <div class="m-2">
      <div class="border rounded p-2 my-2">
        <p>
          <%= simple_format(@place.description) %>
        </p>
      </div>

      <div class="row">
        <% @place.images.each do |image| %>
          <div class="col-md-4">
            <%= link_to image, "data-lightbox" => image  do %>
              <%= image_tag image, class: "img-fluid img-thumbnail d-block mx-auto my-2" %>
            <% end %>
          </div>

        <% end %>
      </div>

      <div id="map" class="my-4" ></div>

      <div class="my-4">
        <% if request.referer&.include?("/places/myplace") %>
          <%= link_to 'My投稿一覧に戻る', places_myplace_path,  data: {"turbolinks" => false} %>
        <% elsif request.referer&.include?("/places/new") %>
          <%= link_to '一覧に戻る', places_path,  data: {"turbolinks" => false} %>
        <% elsif request.referer&.end_with?("/edit") %>
          <%= link_to '一覧に戻る', places_myplace_path,  data: {"turbolinks" => false} %>
        <% else %>
          <%= link_to '投稿一覧に戻る', places_path,  data: {"turbolinks" => false} %>
        <% end %>
      </div>

    </div>

  </div>
</div>

<script src="//maps.google.com/maps/api/js?key=<%= Rails.application.credentials.dig(:google, :api_key) %>&callback=initShowMap" async defer></script>