config/routes.rb
Rails.application.routes.draw do

  # ログインしている場合は投稿一覧がroot
  authenticated :user do
    root to: 'places#index', as: :user_root
  end

  root to: 'pages#index'

  get 'choices/new'
  get 'spots/new'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get 'pages/index'
  get 'pages/about'
  get 'places/myplace'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :comments
  resources :places

end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= bootstrap_alert(key) %>">
    <strong>
      <%= value %>
    </strong>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light fixed-top">
  <div class="container">
    <%= link_to root_path do %>
      <span><%= image_tag "logo.png", class: "navbar-brand logo" %></span>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsContents" aria-controls="navbarsContents" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsContents">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'このサイトの使い方', pages_about_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to '投稿を見る', places_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to '投稿一覧', places_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to '投稿する', new_place_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown"><%= current_user.nickname %></a>
            <div class="dropdown-menu">
              <%= link_to 'My投稿', places_myplace_path, class: "dropdown-item text-dark" %>
              <%= link_to 'プロフィール変更', edit_user_registration_path, class: "dropdown-item text-dark" %>
              <%= link_to 'ログアウト', destroy_user_session_path, class: "dropdown-item text-dark", method: :delete %>
            </div>
          </li>
        <% else %>
          <li>
            <%= link_to '新規登録', new_user_registration_path, id:"new-btn", class: "btn btn-orange" %>
          </li>
          <li>
            <%= link_to 'ログイン', new_user_session_path, id:"login-btn", class: "btn btn-inverse-orange" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThemeParkSpots</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>

  </head>

  <body>
    <%= render 'layouts/flashes' %>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <main>
      <%= yield %>
      <%= javascript_include_tag 'alert.js' %>
      <%= javascript_include_tag 'navbar.js' %>
    </main>
    <footer>
      <p class="copyright">(C) 2020 ThemeParkSpots</p>
    </footer>
  </body>
</html>